//
// Created by fedya on 03.02.17.
//

#ifndef MNE_JOPA_TYPES_H
#define MNE_JOPA_TYPES_H
#endif

DEF_TYPE(TYPE_IF, 1)
DEF_TYPE(TYPE_ELS, 2)
DEF_TYPE(TYPE_IN, 3)
DEF_TYPE(TYPE_OUT, 4)
DEF_TYPE(TYPE_NEW, 5)
DEF_TYPE(TYPE_ASS, 6)
DEF_TYPE(TYPE_RET, 7)
DEF_TYPE(TYPE_END, 8)
DEF_TYPE(TYPE_OP, 13)
DEF_TYPE(TYPE_STRING, 14)
DEF_TYPE(TYPE_LBR, 15)
DEF_TYPE(TYPE_RBR, 16)
DEF_TYPE(TYPE_NUMBER, 20)
DEF_TYPE(TYPE_VAR, 21)
DEF_TYPE(TYPE_FUNC, 22)
DEF_TYPE(TYPE_REG, 23)
DEF_TYPE(TYPE_NEW_FUNC, 24)

